name: lionAPI
version: '${project.version}'
main: de.lioncraft.lionapi.LionAPI
api-version: '1.21'
bootstrapper: de.lioncraft.lionapi.LionBootstrapper
has-open-classloader: true
load: STARTUP
permissions:
  lionapi.timer.main.configure:
    default: op
    description: Sets if a Player can configure the Main Timer.
    children:
      - lionapi.timer.main.see
  lionapi.timer.main.see:
    default: true
    description: Sets if a Player can see the Main Timer.
dependencies:
  server:
    LionUtils:
      required: false
      join-classpath: true
      load: AFTER