name: lionAPI
version: '${project.version}'
main: de.lioncraft.lionapi.LionAPI
api-version: '1.21'
bootstrapper: de.lioncraft.lionapi.LionBootstrapper
has-open-classloader: true
load: STARTUP
dependencies:
  server:
    ProtocolLib:
      required: false
      join-classpath: true
      load: BEFORE